FROM debian:latest

ENV HOME /weechat
ENV TERM xterm-256color

RUN apt-get update && apt-get install -y weechat \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN adduser --disabled-login --gecos '' --home "$HOME" weechat \
    && chown -R weechat:weechat $HOME

USER weechat

WORKDIR $HOME

EXPOSE 2000

CMD ["weechat"]